name: CI

on:
  push:
    branches:
    - '**'
    tags:
    - 'v*'
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**/.*.yml'
    - '.vscode/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, tokenizer
        coverage: none

    - name: Install dependencies
      run: make install-dev
      working-directory: private-captcha

    - name: Lint code
      run: make lint
      working-directory: private-captcha

    - name: Analyze code
      run: make analyze
      working-directory: private-captcha

    - name: Check WordPress coding standards
      run: make wpcs
      working-directory: private-captcha

  package:
    runs-on: ubuntu-latest
    needs: lint
    if: success()

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        tools: wp-cli

    - name: Install dependencies
      run: make install
      working-directory: private-captcha

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: './private-captcha'
        exclude-files: |
          ./private-captcha/.distignore

    - name: Install latest version of dist-archive-command
      run: wp package install wp-cli/dist-archive-command:@stable

    - name: Build plugin
      run: |
        wp dist-archive ./private-captcha ./private-captcha.zip

    - uses: actions/upload-artifact@v4
      with:
        name: wp-plugin
        path: private-captcha.zip
        retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: package
    if: success() && github.ref_type == 'tag'
    environment: GitHub release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wp-plugin

      - name: Display downloaded files
        run: ls -R .

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for ${{ github.ref_name }}" \
            private-captcha.zip
